package antigravity

import (
	"math"
	"sync"
	"time"
)

// Predictor provides an online learning engine for anomaly detection.
// It is designed to run in <200MB memory using simple streaming algorithms.
type Predictor struct {
	mu            sync.Mutex
	metrics       map[string]*OnlineStats
	alpha         float64 // EMA smoothing factor
	anomalyZScore float64 // Threshold for Z-score anomaly detection
}

// OnlineStats holds O(1) memory statistics for online mean/variance calculation (Welford's algorithm)
type OnlineStats struct {
	Count    int64
	Mean     float64
	M2       float64
	EMA      float64
	LastVal  float64
	LastTime time.Time
}

// NewPredictor initializes the prediction engine
func NewPredictor(alpha float64, zScoreThreshold float64) *Predictor {
	return &Predictor{
		metrics:       make(map[string]*OnlineStats),
		alpha:         alpha,
		anomalyZScore: zScoreThreshold,
	}
}

// Observe adds a new observation and returns the current anomaly score
func (p *Predictor) Observe(metricID string, value float64) AnomalyReport {
	p.mu.Lock()
	defer p.mu.Unlock()

	stats, exists := p.metrics[metricID]
	if !exists {
		stats = &OnlineStats{
			Count: 1,
			Mean:  value,
			M2:    0,
			EMA:   value,
		}
		p.metrics[metricID] = stats
		return AnomalyReport{MetricID: metricID, IsAnomaly: false, Score: 0}
	}

	// Update Welford's Algorithm elements
	stats.Count++
	delta := value - stats.Mean
	stats.Mean += delta / float64(stats.Count)
	delta2 := value - stats.Mean
	stats.M2 += delta * delta2

	// Update EMA
	stats.EMA = (p.alpha * value) + ((1 - p.alpha) * stats.EMA)

	stats.LastVal = value
	stats.LastTime = time.Now()

	// Calculate Variance and Z-Score
	variance := stats.M2 / float64(stats.Count)
	stddev := math.Sqrt(variance)

	zScore := 0.0
	if stddev > 0 {
		zScore = math.Abs(value-stats.Mean) / stddev
	}

	isAnomaly := zScore > p.anomalyZScore

	// Predict future value (simple gradient)
	predictedFuture := value + (value - stats.EMA)

	return AnomalyReport{
		MetricID:        metricID,
		IsAnomaly:       isAnomaly,
		Score:           zScore,
		ExpectedValue:   stats.Mean,
		CurrentValue:    value,
		PredictedFuture: predictedFuture,
		Severity:        calculateSeverity(zScore, p.anomalyZScore),
	}
}

// AnomalyReport is the decision generated by the predictor
type AnomalyReport struct {
	MetricID        string  `json:"metric_id"`
	IsAnomaly       bool    `json:"is_anomaly"`
	Score           float64 `json:"score"`
	ExpectedValue   float64 `json:"expected_value"`
	CurrentValue    float64 `json:"current_value"`
	PredictedFuture float64 `json:"predicted_future"`
	Severity        int     `json:"severity"` // 0=OK, 1=Warning, 2=Critical
}

func calculateSeverity(score, threshold float64) int {
	if score > threshold*1.5 {
		return 2 // Critical
	} else if score > threshold {
		return 1 // Warning
	}
	return 0 // OK
}
