{
 "title": "Hawk-Eye",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "HTTP Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "state-timeline",
   "description": "Whether the target is reachable via HTTP.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "hawkeye_health_up", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Roundtrip duration",
   "type": "timeseries",
   "description": "Duration of HTTP roundtrip call to target.",
   "gridPos": { "h": 11, "w": 10, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "hawkeye_latency_seconds", "legendFormat": "{{target}}" }
   ]
  },
  { "title": "DNS Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Health",
   "type": "state-timeline",
   "description": "Whether DNS resolution for the selected target works or not.",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    { "expr": "hawkeye_dns_status", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Resolution duration",
   "type": "timeseries",
   "description": "How long did the DNS resolution need to complete.",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "hawkeye_dns_duration_seconds", "legendFormat": "{{target}}" }
   ]
  }
 ]
}